version: 0.2
phases:
  install:
    commands:
      - echo "This is installing phase"
  pre_build:
    commands:
      - echo "This is pre_build phase"
  build:
    commands:
      - echo "here we can build commands"
  post_build:
    commands:
      - echo "After build this phase will execute"
